### PR TITLE
fixed #77

### LINKED ISSUE #77: AttributeError: 'str' object has no attribute 'joinpath'
Getting below error when calling d.dotslash("../logs") 

```python
  File "/home/hitul/coverfox/env/rblog/local/lib/python2.7/site-packages/speaklater.py", line 186, in __getattr__
    return getattr(self.value, name)
AttributeError: 'str' object has no attribute 'joinpath'
make: *** [run] Error 1
```

### PR DESCRIPTION
**Pull request by hitul007**
- [X] code
- [ ] regression test

### CODE REVIEW

**Comment by juancarlospaco** [comment]
:-1: 

```python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from path import path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named path
>>>
```

```python
Python 3.4.3 (default, Jul 28 2015, 18:20:59)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from path import path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'path'
>>>
```

**Comment by hitul007** [comment]
@juancarlospaco Added dependency to setup.py. Now it'll work.

**Comment by amitu** [comment]
@hitul007, please add some test.

**Comment by juancarlospaco** [comment]
Why do we need `path.py` :grey_question: I never run into a case I can not handle with `os.path` 
Is mandatory to add `path.py` :grey_question: even more considering the new `pathlib` in standard lib now...

**Comment by amitu** [comment]
I think `pathlib` is better, thanks :-). `pathlib` itself is inspired from path.py, which has been part of all my python projects since 12+ years.

This will break some code, but I think we should take the hit now, and fix all those code.

**Comment by juancarlospaco** [comment]
If you gonna add it as mandatory dependency and is better why not use `pathlib` instead :grey_question: 
Its for python2 also according to itself and pypi, and you dont need anything for python3...

**Comment by hitul007** [comment]
@juancarlospaco Thanks for suggesting pathlib. I tried it but it is not working in Logger. It don't have startswith method. Logger is raising an exception. So, I think we should continue with pathpy.

**Comment by amitu** [comment]
Damn, 0.5.0 :-). I would have made it 0.4.1 :-)

**Comment by hitul007** [comment]
Okay. Let me change it.

**Comment by juancarlospaco** [comment]
SemVer explains when you should change one or another number...

**Comment by hitul007** [comment]
@amitu Sent a PR with 0.4.1.

**Pull request merged**
