### PR TITLE
Fixed #79

### LINKED ISSUE #79: Django middleware's process view not called
Django middleware's `process_view` is skipped because importd SmartReturnMiddleware added at index `0` and returns `HttpResponse`. As per django document https://docs.djangoproject.com/en/1.8/topics/http/middleware/#process_view if some middleware returns `HttpResponse` then other middlewares `process_view` will not be called.

### PR DESCRIPTION
**Pull request by hitul007**
- Fixed #79 
- Extra python path can be added into d as kwargs argument ENVDIR.

### CODE REVIEW

**Comment by juancarlospaco** [comment]
:+1:

**Comment by juancarlospaco** [comment]
Mmm, it adds mandatory Dependencies, IMHO lets wait to see @amitu 's thumbs-up...  :smile_cat:

**Comment by hitul007** [comment]
Ok

**Comment by amitu** [comment]
I think its a good idea to have envdir support.

**Pull request merged**
